language: python
python:
  - "2.6"
  - "2.7"
install:
  - pip install --timeout=30 pep8 --use-mirrors
  - pip install --timeout=30 https://github.com/dcramer/pyflakes/tarball/master
  - pip install --timeout=30 -q -e . --use-mirrors
before_script:
  - "pep8 --exclude=migrations --ignore=E501,E225 django_transfer"
  - pyflakes -x W django_transfer
script:
  - python tests.py
